bun.lock, packages/vscode/src/integrations/mcp/third-party-mcp/providers/base-file-provider.ts, packages/vscode/src/integrations/mcp/third-party-mcp/providers/path-utils.ts, packages/vscode/src/integrations/mcp/third-party-mcp/providers/vscode-provider.ts
- Refactored the VS Code MCP importer provider, improving modularity and readability.
- Introduced `path-utils.ts` to centralize and simplify path-related logic.
- Updated `vscode-provider.ts` and `base-file-provider.ts` to use the new path utilities.
- The changes have been manually verified in a local development environment.
- All related unit tests continue to pass successfully.
=> feat(vscode): refactor mcp importer provider

bun.lock, packages/vscode-webui/src/features/settings/components/sections/account-section.tsx, packages/vscode-webui/src/features/settings/components/sections/mcp-section.tsx, packages/vscode-webui/src/features/settings/components/sections/model-section.tsx
- Increases the clickable area and improves the hover/focus styles for the edit buttons on the settings page, making them easier to interact with.
Manual testing of the settings page to confirm the improved interaction.
=> feat(webui): improve ux of settings page edit buttons

bun.lock, packages/docs/package.json, packages/vscode-webui/src/components/task-thread.tsx
- Adjusts the border style for the new task component for better visual consistency. This change replaces a custom border color with the standard theme border.
N/A
=> fix(webui): adjust new task border style

packages/livekit/src/chat/generate-task-title.ts, packages/livekit/src/chat/llm/types.ts
- Remove unused system parameter in generateTitle function
- Make system parameter optional in LLMRequest type
This change cleans up the task title generation code by removing an unused parameter and making the system parameter optional in the LLMRequest type.
=> fix(livekit): do not set system prompt for title generation, to fix anthropic models

packages/livekit/src/chat/llm/pochi.ts
- Add logger to PochiModel
- Implement graceful shutdown handling for SIGTERM and SIGINT signals
- Ensure all pending jobs are processed before shutdown
- Add shutdown state tracking to prevent multiple shutdown attempts
This change improves the reliability of the Pochi model by ensuring that all pending operations are completed before the process exits.
=> feat: add graceful shutdown to Pochi model PersistManager

packages/common/src/base/constants.ts
- Remove unused SandboxPath constants that are no longer needed in the codebase
- Clean up KnownTags documentation that was no longer being used
These constants appear to be remnants from previous implementations and are not currently referenced anywhere in the codebase.
=> chore(constants): remove unused sandbox path constants

packages/common/src/tool-utils/__tests__/credential-storage.test.ts, packages/common/src/tool-utils/credential-storage.ts
- Replace interface with zod schema for PochiCredential
- Add validation when reading and writing credentials
- Remove unused test case for updating existing token
- Improve type safety with zod validation
=> feat(common): add zod validation to credential storage

packages/docs/content/docs/developer-updates.mdx, packages/docs/content/docs/meta.json
We want a central place to track Pochi’s weekly progress — not just releases, but also enhancements, bug fixes, and developer insights. This page acts as a lightweight changelog + digest that’s easier for contributors and users to follow.
- Added `developer updates` page
- Added this week's(Aug 24 - 28th) updates
=> docs: add developer updates page & this week's digest

packages/common/src/tool-utils/__tests__/ignore-walk.test.ts, packages/vscode-webui/src/features/chat/lib/tool-call-life-cycle.ts, packages/vscode-webui/src/features/chat/lib/use-tool-call-life-cycles.ts
This commit updates the tool call lifecycle management in the web UI. It ensures that tool calls in the 'ready' state are correctly handled when a user aborts an operation and are properly identified as previewing tool calls.
This fixes a bug where aborting a tool call in the `ready` state would not properly transition it to the `complete` state with an error.
- Manually verified that aborting a tool call in the `ready` state now correctly transitions it to the `complete` state.
- Existing automated tests pass.
=> fix(webui): handle ready state in tool call lifecycle

packages/cli/src/task-runner.ts, packages/livekit/src/chat/flexible-chat-transport.ts, packages/livekit/src/chat/live-chat-kit.ts, packages/livekit/src/react.tsx, packages/tools/src/index.ts
This PR updates the tool selection mechanism to support environment-specific configurations, introducing proper separation between CLI and non-CLI environments.
- **Refactored tool selection**: Updated `selectClientTools` to accept configuration options instead of a simple boolean
- **Environment-specific tools**: Added `isCli` parameter to distinguish between CLI and non-CLI environments  
- **Tool set separation**: Split tools into CLI-specific and full client toolsets for appropriate functionality
- **Core component updates**: Updated LiveChatKit, FlexibleChatTransport, and React hooks to handle CLI context
- `packages/tools/src/index.ts` - Refactored tool selection logic
- `packages/cli/src/task-runner.ts` - Added CLI identification
- …
=> chore: add CLI-specific tool selection and configuration

packages/common/src/tool-utils/custom-rules.ts, packages/common/src/tool-utils/index.ts, packages/vscode/src/lib/env.ts
- Rename SystemRulesFilepath to GlobalRules with improved structure
- Rename DefaultWorkspaceRulesFilePaths to WorkspaceRulesFilePaths
- Add support for POCHI_CUSTOM_INSTRUCTIONS environment variable
- Update imports and references accordingly
This change improves the organization of rule files by renaming "system rules" to "global rules" which better reflects their purpose. It also adds support for custom instructions via environment variables, providing more flexibility for users.
=> refactor: rename system rules to global rules and add env var support

packages/cli/src/tools/__test__/execute-command.test.ts, packages/cli/src/tools/execute-command.ts
- Enhanced the executeCommand tool to properly handle command exit codes
- Added execWithExitCode helper function to capture exit codes from command execution
- Modified the tool to return an error field for non-zero exit codes instead of throwing exceptions
- Updated tests to match the new behavior
- Improved error message handling
=> feat(cli): enhance executeCommand tool to handle exit codes properly

packages/cli/src/cli.ts, packages/cli/src/lib/__tests__/workflow-loader.test.ts, packages/cli/src/lib/workflow-loader.ts, packages/cli/src/output-renderer.ts, packages/common/src/base/constants.ts, packages/common/src/base/prompts/index.ts, packages/common/src/message-utils/index.ts, packages/common/src/message-utils/markdown.ts, packages/vscode-webui/src/components/prompt-form/workflow-mention/extension.tsx
This PR implements workflow support for the CLI as requested in issue #109. Users can now reference workflows directly in the CLI by using `/workflow-name` syntax.
For example:
```bash
pochi -p "/create-pr"
```
This will automatically load the workflow content from `.pochi/workflows/create-pr.md` and use it as the prompt.
Additionally, this PR adds markdown parsing utilities to improve how text is displayed in the CLI output.
- Added `workflow-loader` utility to handle loading workflow files
- Updated CLI argument parsing to detect and process workflow references
- Added comprehensive tests for the workflow loading functionality
- Updated help text to document the new feature
- Added markdown parsing utilities for better text rendering in CLI output
- Updated CLI output renderer to use …
=> feat(cli): add workflow support to CLI with markdown parsing

packages/cli/src/cli.ts, packages/cli/src/tools/write-to-file.ts
- Changes the error message for missing workflows to a warning, allowing the CLI to continue execution.
- Fixes a bug in the `writeToFile` tool by awaiting the `isFileExists` function, ensuring correct asynchronous behavior.
=> fix(cli): handle missing workflows gracefully and fix async bug in writeToFile

packages/vscode-webui/src/features/retry/hooks/use-pending-model-auto-start.ts
- Added useAutoApproveGuard hook to ensure tasks have proper approval context when auto-starting pending model tasks
- Set autoApproveGuard.current = true when automatically starting pending model tasks to prevent permission issues
- Updated useEffect dependencies to include autoApproveGuard for proper reactivity
When tasks are automatically started from pending-model state, they need to have the proper approval context to ensure subsequent operations (like file modifications) are allowed to proceed without manual approval prompts.
=> fix: add auto-approve guard to pending model auto-start hook

packages/vscode-webui/src/features/chat/components/error-message-view.tsx
https://jam.dev/c/1872f95c-90f6-4c93-9e2f-dab3501b3249
- This change debounces the error state in `ErrorMessageView` to prevent the error message from blinking when it updates frequently.
- Manually verified that the error message no longer blinks on rapid updates.
=> fix(webui): debounce error message to prevent blinking

assets/config.schema.json, packages/cli/src/cli.ts, packages/common/src/configuration/model.ts, packages/docs/content/docs/models.mdx, packages/vscode-webui/src/features/settings/components/sections/model-section.tsx, packages/vscode-webui/src/features/settings/hooks/use-models.ts, packages/vscode/src/integrations/command.ts
- Update model configuration schema to use record/object structure instead of array
- Modify CLI, WebUI, and VSCode integration to work with new record-based model configuration
- Update documentation to reflect the new configuration format
- Updated `packages/common/src/configuration/model.ts` to change models from array to record structure
- Modified `packages/cli/src/cli.ts` to access models using record syntax
- Updated `packages/vscode-webui/src/features/settings/components/sections/model-section.tsx` to handle record-based models
- Updated `packages/vscode-webui/src/features/settings/hooks/use-models.ts` to process record-based models
- Updated `packages/vscode/src/integrations/command.ts` example configuration
- Updated `packages/docs/content/docs/models.mdx` documentation
- …
=> chore: change model configuration from array to record structure

assets/config.schema.json, packages/common/src/configuration/gen-schema.ts, packages/common/src/configuration/model.ts, packages/common/src/configuration/types.ts
This PR improves the configuration schema handling and documentation clarity.
- Updated model provider name description for better clarity
- Restructured PochiConfig creation to use a helper function for runtime vs schema generation
- Enhanced handling of optional configuration entries
- Fixed JSON schema generation compatibility
All tests pass and schema generation works correctly.
=> chore(config): loose type validation for providers / mcp

packages/docs/content/docs/cli.mdx
This PR adds documentation for installing the Pochi CLI using Homebrew.
N/A
=> docs(cli): add install using homebrew

packages/common/src/base/prompts/environment.ts, packages/common/src/base/prompts/index.ts
- Add a new function `isEnvironmentSystemReminder` to specifically identify environment-related system reminders (those that include "# TODOs")
- Update the `injectEnvironment` function to use this more specific function instead of the general `isSystemReminder` to better control which system reminders are filtered out
- Export the new function in the prompts index
This change allows for more precise control over system reminders in the environment context, enabling better customization of what gets filtered out when injecting environment information.
=> fix(common): add environment-specific system reminder filtering

packages/vscode/src/integrations/editor/__test__/diff-view.test.ts, packages/vscode/src/integrations/editor/diff-view.ts
Closes #160 — Automatically close non-diff editor tabs when opening a diff view.
- Added tab cleanup logic to `openDiffEditor()` and `runVSCodeDiff()`
- Added unit tests with proper mocking
- Preserves diff tabs, closes only regular text editor tabs
=> feat: close existing file buffer when opening diff view (#160)

bun.lock, packages/livekit/package.json, packages/livekit/src/chat/models/vendor.ts, packages/vscode-webui/vite.config.js
- Fixed vscode-webui build issues by adding browser-safe aliases for Node.js-specific modules in vite.config.js
- Added resolve.alias configuration to stub out server-side dependencies that were causing build failures in browser environment
=> fix(vscode-webui): disable gemini cli vendor temporarily to fix vscode webui build

packages/vscode-webui/src/components/tool-invocation/tools/attempt-completion.tsx, packages/vscode-webui/src/features/approval/components/retry-approval-button.tsx, packages/vscode-webui/src/i18n/locales/en.json, packages/vscode-webui/src/i18n/locales/jp.json, packages/vscode-webui/src/i18n/locales/ko.json, packages/vscode-webui/src/i18n/locales/zh.json
This pull request removes internationalization (i18n) support for several UI strings in the tool invocation and approval components, replacing dynamic translations with hardcoded English text. It also deletes related translation keys from all language JSON files. This simplifies the codebase but means these UI messages will no longer be localized.
**Internationalization removal:**
* Removed `useTranslation` and translation calls from `AttemptCompletionTool` and `RetryApprovalButton` components, replacing them with hardcoded English strings for "Task Completed", "Continue", "Continue in Xs", and "Cancel". (`packages/vscode-webui/src/components/tool-invocation/tools/attempt-completion.tsx`, `packages/vscode-webui/src/features/approval/components/retry-approval-button.tsx`) …
=> refactor: remove translation dependencies and replace with hardcoded text

packages/common/src/vscode-webui-bridge/webview-stub.ts, packages/common/src/vscode-webui-bridge/webview.ts, packages/vscode-webui/src/components/tool-invocation/command-execution-panel.tsx, packages/vscode-webui/src/components/tool-invocation/tools/kill-background-job.tsx, packages/vscode-webui/src/components/tool-invocation/tools/read-background-job-output.tsx, packages/vscode-webui/src/components/tool-invocation/tools/start-background-job.tsx, packages/vscode-webui/src/features/chat/index.ts, packages/vscode-webui/src/features/chat/lib/use-background-job-display.tsx, packages/vscode-webui/src/lib/hooks/use-visible-terminals.ts, packages/vscode-webui/src/lib/vscode.ts, packages/vscode/src/integrations/terminal/terminal-state.ts, packages/vscode/src/integrations/webview/vscode-host-impl.ts
- https://jam.dev/c/96aae672-3195-4804-88bf-0f8e79ac0a62
This feature makes the background job ID a link that, when clicked, reveals the corresponding terminal in the VS Code panel. This improves the user experience by providing a quick way to navigate to the terminal running the background job.
- Run a background job.
- Verify that the job ID in the web UI is a clickable link.
- Click the link and confirm that it opens the correct terminal.
=> feat(webui): add terminal link for background jobs

packages/cli/src/auth/cmd.ts, packages/cli/src/auth/login/index.ts
- Update getLoginFn to accept command parameter for better error handling
- Add specific handling for pochi vendor with informative error message
- Improve unknown vendor error messaging
This change enhances the authentication command by providing more specific error messages when logging in with different vendors, particularly adding guidance for Pochi users to use the VS Code extension.
=> chore(cli): improve auth login vendor handling

.github/workflows/release-pochi-cli.yml, packages/cli/scripts/npm-release.ts
Test CI: https://github.com/zwpaper/pochi/actions/runs/17511635315/job/49743974435
failed because the 0.5.0-dev pushed before to my test npm
=> fix(ci): copy npmrc to release project when push to npm

packages/livekit/src/chat/llm/repair-tool-call.ts
This PR adds logging to the tool call repair logic in `packages/livekit/src/chat/llm/repair-tool-call.ts`.
No new tests were added as this is a logging change.
=> feat(livekit): add logging to tool call repair

packages/common/src/vendor/edge.ts, packages/common/src/vendor/node.ts, packages/common/src/vendor/registry.ts
- Implement generic `createRegistry` function for type-safe registries
- Refactor vendor management in node.ts to use centralized registry instead of direct object storage
- Refactor model management in edge.ts to use centralized registry with consistent error handling
- Remove duplicate registry logic and improve maintainability across vendor system
- Maintain backward compatibility with existing vendor/model APIs
=> refactor: create centralized registry for vendors and models

packages/cli/scripts/npm-release.ts
Passed CI: https://github.com/zwpaper/pochi/actions/runs/17515523922/job/49752544486
Published pochi under custom org: https://www.npmjs.com/package/@kweizh/pochi
install and test:
=> fix(ci): cli in npm should publish as public package

assets/config.schema.json, packages/cli/src/cli.ts, packages/common/src/configuration/types.ts, packages/common/src/configuration/vendor.ts, packages/vendor-gemini-cli/src/types.ts, packages/vendor-gemini-cli/src/vendor.ts, packages/vendor-pochi/src/constants.ts, packages/vendor-pochi/src/edge.ts, packages/vendor-pochi/src/model.ts, packages/vendor-pochi/src/node.ts, packages/vendor-pochi/src/types.ts, packages/vendor-pochi/src/vendor.ts, packages/vscode/src/lib/token-storage.ts
This pull request refactors the vendor configuration by introducing vendor-specific types, which simplifies the overall structure and improves type safety.
- **Vendor-Specific Types**: Created dedicated type definitions for each vendor (`pochi`, `gemini-cli`) to better represent their unique credential and user structures.
- **Simplified Configuration**: Refactored the main vendor configuration to use a more generic structure, removing hardcoded properties for each vendor.
- **Updated JSON Schema**: Modified `assets/config.schema.json` to validate the new, more flexible vendor configuration format.
- **Code Cleanup**: Removed the obsolete `packages/vendor-pochi/src/constants.ts` file.
- All existing tests have passed successfully during the pre-push hook execution.
🤖 Generated with …
=> refactor: introduce vendor-specific types and simplify vendor configuration

packages/vscode/src/lib/custom-agent.ts
This adds try...catch blocks around the file system watchers for custom agents to prevent the extension from crashing if there are errors during watcher initialization.
=> fix(vscode): handle errors in custom agent file watchers

packages/vscode-webui/src/components/prompt-form/auto-completion/extension.ts, packages/vscode-webui/src/components/prompt-form/auto-completion/mention-list.tsx, packages/vscode/src/integrations/webview/vscode-host-impl.ts
- Improves the responsive design of the autocomplete mention list.
- Adjusts the min-width to be 150px on small screens and 200px on larger screens.
- Adjusts the max-width to be 250px on small screens and 350px on larger screens.
https://jam.dev/c/2bfac4d2-4026-4b34-95ac-1ef543a7c86b
=> fix: improve responsive design for autocomplete mention list

packages/livekit/src/chat/flexible-chat-transport.ts, packages/tools/src/custom-agent.ts, packages/tools/src/index.ts
This commit introduces a `general-purpose` agent that is now always available by default. This is achieved by adding an `overrideCustomAgents` function that ensures the `general-purpose` agent is always included in the list of custom agents. This simplifies the configuration and ensures that a fallback agent is always present.
- Run existing tests to ensure no regressions.
=> feat: make general-purpose agent always available

packages/vscode-webui/src/components/prompt-form/shared.tsx
This change adds the ability to use the Tab key to select an item from the mention list in the prompt form.
N/A
=> chore(webui): allow using Tab to select mention

packages/vscode/package.json, packages/vscode/src/integrations/command.ts
This PR introduces a new command `pochi.loginWithToken` that allows users to log in by manually providing a token. This serves as a robust fallback mechanism for environments where the browser-based authentication flow may fail.
https://jam.dev/c/989d4c11-5c0e-4862-8cb4-af33f77d0a57
- Added `pochi.loginWithToken` command to `packages/vscode/src/integrations/command.ts`
- The command prompts the user for a token and uses a direct authentication flow, independent of URI handlers
- Registered the new command in `package.json` under `contributes.commands` and `contributes.menus.commandPalette` to make it accessible in the command palette
=> feat: add command to login with token

bun.lock, packages/common/src/base/prompts/__tests__/__snapshots__/prompt.test.ts.snap, packages/common/src/base/prompts/system.ts, packages/vscode-webui/package.json, packages/vscode-webui/src/components/message/__stories__/mermaid.stories.tsx, packages/vscode-webui/src/components/message/code-block.tsx, packages/vscode-webui/src/components/message/mermaid.tsx, packages/vscode-webui/src/types/mermaid-js__tiny.d.ts
This commit introduces support for rendering Mermaid diagrams in the web UI.
- Added the `mermaid` package as a dependency.
- Created a new `Mermaid` component to render diagrams.
- Updated the `CodeBlock` component to switch between code view and diagram view for mermaid code blocks.
- Added storybook stories for the `Mermaid` component.
=> feat(webui): add mermaid diagram support

packages/vscode/src/lib/user-storage.ts
- https://jam.dev/c/0a180633-1589-4d8b-b14c-51917b057d09
This change ensures that when the user deletes the `~/.pochi/config.jsonc` file, the user information is cleared from the cache. This will ensure that the UI accurately reflects the user's logged-out state.
1. Run the VS Code extension.
2. Log in.
3. Observe user info in the settings page.
4. Delete `~/.pochi/config.jsonc`.
5. Observe that the settings page now shows the login view.
=> fix(vscode): clear user cache on config deletion

bun.lock, packages/cli/package.json, packages/cli/src/auth/cmd.ts, packages/cli/src/auth/vendor-selector.ts
https://jam.dev/c/bc86bbbb-ae5c-42e2-ad9d-8f715d8570cd
• Add interactive vendor selection for authentication commands using inquirer
• Improve error handling for authentication cancellation scenarios
• Replace required vendor flags with user-friendly selection prompts
• Add support for showing authentication status in vendor selection
• **Interactive Selection**: Replace `-v, --vendor` required option with interactive prompts using `@inquirer/select`
• **Enhanced UX**: Show authentication status and user information in vendor selection
• **Better Error Handling**: Handle user cancellation (Ctrl+C) gracefully for both login and logout
• **Smart Defaults**: Auto-select single vendor when only one is available
• **Improved Logout**: Interactive selection from authenticated vendors with user …
=> feat(cli): add interactive vendor selection for auth commands

packages/vscode-webui/src/components/prompt-form/auto-completion/mention-list.tsx, packages/vscode-webui/src/components/prompt-form/form-editor.tsx
https://jam.dev/c/d8420180-b154-4b3b-9ad1-68d51eed74e9
- Allow form submission with Enter key in autocomplete when no suggestions are available.
- Adjust padding and alignment in the form editor for better UI consistency.
- Manually tested the form submission in the web UI.
=> fix(webui): improve prompt form submission and styling

packages/vscode-webui/src/components/prompt-form/auto-completion/extension.ts
https://jam.dev/c/6b4d157b-7a14-4262-87d6-fcb37ebfb68b
- Adds a debounce to the hint plugin to delay showing the hint.
- Hides the hint immediately when it's no longer needed.
=> chore(vscode-webui): add debounce to hint plugin

packages/docs/content/docs/tab-completion.mdx
This PR adds documentation for the tab completion model settings, explaining how to configure a custom OpenAI-compatible server for code completion.
N/A
----
#23
=> docs: add documentation for tab completion model settings

packages/github-action/src/run-pochi.ts
- Added stderr output to process in GitHub Action to improve error visibility when running Pochi
This change ensures that stderr from the Pochi process is written to the GitHub Actions stderr, making error messages visible in the action logs.
Co-Authored-By: Pochi <noreply@getpochi.com>
https://github.com/Sma1lboy/pochi/actions/runs/17741640047/job/50416789819
=> feat(github-action): output stderr to process for better error visibility

packages/docs/content/docs/permissions.mdx, packages/docs/content/docs/rules.mdx, packages/docs/content/docs/share.mdx, packages/docs/content/docs/tab-completion.mdx, packages/docs/content/docs/vscode.mdx, packages/docs/src/app/(docs)/[[...slug]]/page.tsx
- As we add more dev updates, TOC on the right side is cluttered with the `<h3>`s, such as `TL;DR`, `Enhancements` etc
- Locally, some doc pages render with error `In HTML, <p> cannot be a descendant of <p>. This will cause a hydration error.`
- Only render `h1` and `h2` in TOC for dev updates page.
- Wrap images inside of `<div>` instead of `<p>`
=> docs: improve TOC for dev updates page and fix image containers

packages/vscode-webui/src/features/settings/components/auto-approve-menu.tsx
https://jam.dev/c/1d53a6a6-aeb8-42fa-9616-5e61dcde5c63
Refactored the auto-approve settings menu to enhance user experience by making the entire retry action area clickable. This improves usability by allowing users to click the label text to toggle the retry functionality.
Manual testing of the settings page to confirm the new clickable area works as expected.
=> chore(vscode-webui): Make auto-approve retry action label clickable

packages/common/src/vscode-webui-bridge/webview-stub.ts, packages/common/src/vscode-webui-bridge/webview.ts, packages/vscode/src/integrations/webview/vscode-host-impl.ts
- Update VSCodeHostApi.readStoreId() to return Promise<string> instead of Promise<string | undefined>
- Modify VSCodeHostImpl.readStoreId() implementation to always return a store ID, using "default" when no workspace is available
- Update webview-stub.ts to match the new signature
- This change ensures consistent behavior when accessing store IDs across the application
=> fix(vscode-webui): update readStoreId to always return a string

packages/vscode-webui/src/routes/index.tsx, packages/vscode-webui/src/routes/tasks.tsx
- Renamed search parameter from `createdAt` to `storeDate` in index.tsx
- Updated TaskRow component to use `storeDate` parameter  
- Consistently use `storeDate` naming convention across the webui
=> refactor: rename createdAt to storeDate in vscode-webui routes

packages/vscode-webui/src/livestore-provider.tsx, packages/vscode-webui/src/routes/index.tsx, packages/vscode-webui/src/routes/tasks.tsx
- Rename `date` and `setDate` variables to `storeDate` and `setStoreDate` respectively in the LiveStoreProvider and related components
- Update all references in the routes components
- Add date prop to EmptyTaskPlaceholder to show the date in the UI
This change improves code clarity and maintainability by using more descriptive variable names that better reflect their purpose.
=> refactor(vscode-webui): rename date to storeDate for clarity

packages/vscode-webui/src/features/approval/components/retry-approval-button.tsx, packages/vscode-webui/src/features/approval/components/tool-call-approval-button.tsx, packages/vscode-webui/src/features/approval/hooks/use-pending-retry-approval.ts, packages/vscode-webui/src/features/chat/components/chat-toolbar.tsx, packages/vscode-webui/src/features/chat/hooks/use-chat-submit.ts, packages/vscode-webui/src/features/chat/lib/chat-state/chat.tsx, packages/vscode-webui/src/features/chat/lib/chat-state/fixed-state.tsx, packages/vscode-webui/src/features/chat/lib/chat-state/types.ts, packages/vscode-webui/src/features/chat/page.tsx, packages/vscode-webui/src/features/retry/hooks/use-pending-model-auto-start.ts
- Replace boolean values with descriptive enum values ("auto" | "manual" | "stop") for the autoApproveGuard
- Enhance code readability and maintainability of the auto-approval system
- Make the different modes of operation more explicit and understandable
=> refactor(vscode-webui): improve auto-approval guard with enum values

.github/workflows/release-pochi-cli.yml
This PR fixes an issue where the CLI entry point was incorrect when packaging for npm.
=> fix(cli): correct the right cli entry when packaging npm

packages/livekit/src/chat/live-chat-kit.ts, packages/livekit/src/livestore/schema.ts, packages/vscode-webui/src/components/public-share-button.tsx, packages/vscode-webui/src/features/chat/components/chat-toolbar.tsx, packages/vscode-webui/src/features/chat/page.tsx, packages/vscode-webui/src/i18n/locales/en.json, packages/vscode-webui/src/i18n/locales/jp.json, packages/vscode-webui/src/i18n/locales/ko.json, packages/vscode-webui/src/i18n/locales/zh.json
This commit introduces a new feature that allows users to control the visibility of their shared tasks. Users can now toggle between 'public' (anyone with the link can view) and 'private' (only the user can view).
Changes include:
- Updated the `LiveChatKit` to handle public share status updates.
- Modified the `livestore` schema to include an `isPublicShared` boolean flag.
- Enhanced the `PublicShareButton` component to provide options for toggling the share status.
- Added new localization strings for the public/private options.
- Manually tested the share button functionality in the chat interface.
- Verified that the `isPublicShared` status is correctly updated in the backend.
=> feat(share): add public sharing option for tasks

packages/vscode-webui/src/features/chat/docs/use-auto-approve-guard.md, packages/vscode-webui/src/features/chat/hooks/use-chat-submit.ts
This PR improves the auto-approve guard flow in the chat submit hook and adds comprehensive documentation for the autoApproveGuard mechanism.
- Repositions the autoApproveGuard update in `use-chat-submit.ts` to ensure consistent behavior when sending messages
- The guard is now set to "auto" mode immediately after sending messages, regardless of the path taken
- Adds comprehensive documentation for the autoApproveGuard mechanism explaining:
- Its role as a gatekeeper for agent execution flow
- The three execution modes: "auto", "manual", and "stop"
- Core components and approval/continuation flow
- A Mermaid diagram illustrating the decision-making process
=> fix(vscode-webui): improve auto-approve guard flow in chat submit

packages/vscode-webui/src/features/retry/hooks/use-retry.ts
- Removes the condition that prevents retrying API calls when `error.isRetryable` is `false`.
- This allows users to manually trigger a retry for any failed API call, providing more control over error handling.
- Verify the change in `packages/vscode-webui/src/features/retry/hooks/use-retry.ts` removes the intended logic.
- Run `bun run test` to ensure all existing tests pass.
=> fix(webui): allow retry on all API call errors

packages/common/src/pochi-api.ts, packages/livekit-cf/src/do/livestore-client/do.ts
- Remove unused UIMessage and Environment imports from pochi-api.ts
- Remove unused messages field from PersistRequest schema
- Simplify clientTaskData persistence in LiveStoreClientDO by passing the entire task object instead of destructuring individual properties
=> refactor: remove unused imports and simplify task persistence data

packages/cli/src/lib/load-agents.ts, packages/common/src/tool-utils/__tests__/agent-parser.test.ts, packages/common/src/tool-utils/agent-parser.ts, packages/docs/content/docs/custom-agent.mdx, packages/vscode/src/lib/custom-agent.ts
This pull request updates the documentation for custom agents to align with the current implementation.
- The `name` field in the frontmatter is now correctly documented as optional. If omitted, the agent's filename (without the extension) is used as its name.
- The documentation for the `tools` field has been updated to clarify that it can be either a comma-separated string or a YAML array.
- An example has been updated to reflect these changes.
- Verified the documentation renders correctly.
- Ensured the updated information matches the behavior of the agent parser.
=> chore: simplify custom agent definition

bun.lock, packages/livekit/src/chat/flexible-chat-transport.ts
- Fix issue where tools were not being properly passed to the model in FlexibleChatTransport
- Extract tools selection logic to avoid duplication
- Pass tools to convertToModelMessages to ensure proper tool handling
=> fix(chat): ensure tools are properly passed to flexible chat transport

packages/vscode-webui/src/features/chat/hooks/use-chat-submit.ts
This PR refactors the chat submit hook to improve how queued messages are handled:
- Move setQueuedMessages([]) to execute earlier in the flow
- Add a comment explaining the purpose of clearing queued messages
- Reorder operations to ensure messages are properly collected before clearing
This ensures that queued messages are properly processed and cleared in a more predictable manner.
=> fix(chat): improve queued messages handling in chat submit

packages/vendor-gemini-cli/src/model.ts
This PR fixes an issue where the gemini-cli model would not correctly handle non-ok responses from the API. This change ensures that we throw an error when the response is not `ok`.
Existing tests should cover this.
=> fix(vendor-gemini-cli): handle non-ok responses in fetch

packages/vscode-webui/src/components/ui/calendar.tsx, packages/vscode-webui/src/routes/tasks.tsx
- Add `startMonth` to hide unnecessary years and fix year select panel overflow.
- Add `defaultMonth` to default the calendar picker to the selected value.
- Add "Today" button for quick navigation.
Co-Authored-By: Pochi <noreply@getpochi.com>
=> chore(calendar): improve calendar usability with new features

packages/livekit-cf/src/do/livestore-client/app.ts, packages/livekit-cf/src/do/livestore-client/do.ts, packages/livekit-cf/src/do/livestore-client/types.ts, packages/livekit-cf/src/types.ts, packages/livekit-cf/src/worker.ts, packages/livekit/src/livestore/queries.ts
- Refactors `user` to `owner` in `livekit-cf` and `livekit` for clarity on ownership.
- Introduces an endpoint to reload shared tasks for the store owner.
- Enhances security with an ownership check middleware for protected endpoints.
- All existing tests should continue to pass.
- The new `POST /tasks/share` endpoint should be tested to ensure it reloads tasks correctly for the owner.
- Access to owner-only endpoints should be denied for non-owners.
=> refactor(livekit): rename user to owner and add task reload

packages/vendor-codex/src/auth.ts, packages/vendor-codex/src/model.ts, packages/vendor-codex/src/utils.ts
- Move extractAccountId function from auth.ts to new utils.ts file
- Update imports in model.ts to use the new utils module
- Clean up unused AuthClaims import in auth.ts
=> refactor(vendor-codex): move extractAccountId to utils module

packages/common/src/pochi-api.ts, packages/vscode/src/code-completion/client/pochi.ts
- Remove unused FIM API types from pochi-api.ts
- Update Pochi code completion client to use direct API calls instead of ApiClient
- Switch to using getVendor for credentials
- Update request/response types to match Mistral API format
- Change maxTokens to max_tokens to match API expectations
=> refactor(vscode): update pochi code completion client to use direct API

packages/tools/src/index.ts, packages/vendor-pochi/src/tools/index.ts, packages/vendor-pochi/src/tools/web-fetch.ts, packages/vendor-pochi/src/tools/web-search.ts, packages/vendor-pochi/src/vendor.ts, packages/vscode-webui/src/components/tool-invocation/mcp-tool-call.tsx
- Move existing webFetch tool implementation to separate module
- Add new webSearch tool for Pochi vendor
- Implement makeWebFetch and makeWebSearch functions in separate modules
- Improve tool result UI with separators for better readability
- Update tools permission list to include new web tools
- Fix webSearch execute function parameter type
These changes refactor the existing webFetch tool into a separate module and add a new webSearch tool, providing more comprehensive web interaction capabilities. The UI improvements make tool results easier to read and understand.
=> feat: refactor webFetch and add webSearch tools to Pochi vendor with UI improvements

packages/vendor-qwen-code/src/model.ts, packages/vendor-qwen-code/src/vendor.ts
- Add model ID mapping to support Qwen VL Max vision model
- Map "qwen-vl-max" to "vision-model" for API compatibility
- Update model configuration to include qwen-vl-max with 128k context window
- Remove qwen3-coder model from configuration
- Added `ModelIdMap` to map user-facing model IDs to API-specific model identifiers
- Updated `createQwenModel` to use the mapped model ID
- Replaced qwen3-coder configuration with qwen-vl-max configuration
=> fix(vendor-qwen-code): Add Qwen VL Max vision model support

packages/cli/src/cli.ts
- Fix CLI shutdown sequence by calling renderer.shutdown() before displaying share URL
- Remove duplicate task link rendering in output
- Add comment about hardcoded URL
=> fix(CLI): duplicate task completed rendering

packages/cli/src/cli.ts, packages/cli/src/livekit/store.ts, packages/cli/src/task/cmd.ts
- Replace POCHI_LIVEKIT_NO_SYNC with POCHI_LIVEKIT_SYNC_ON for clearer semantics
- Update storage configuration to use enableSync flag instead of disableSync flag
- Add conditional registration for task command based on sync enablement
This change improves the configuration logic for LiveKit sync by using a positive enable flag instead of a negative disable flag, making the code more intuitive.
=> feat(cli): turn off LiveKit sync configuration by default

bun.lock, packages/cli/package.json, packages/cli/src/lib/load-agents.ts
This PR addresses an issue where duplicate custom agents could be loaded. It introduces the `remeda` library and utilizes its `uniqueBy` function to ensure that agents are unique by name before being loaded.
This change involves:
- Adding `remeda` as a dependency in `packages/cli/package.json`.
- Updating `packages/cli/src/lib/load-agents.ts` to use `uniqueBy` to filter out duplicate agents.
- The `bun.lock` file has been updated accordingly.
The pre-push hooks which run tests have passed. Manual verification of agent loading should confirm that only unique agents are loaded.
=> fix(cli): prevent duplicate agents by using remeda's uniqueBy

packages/cli/src/task-runner.ts
This PR changes the task runner logic to return "retry" instead of "next" when handling certain message scenarios. This ensures proper retry behavior in the task execution flow.
Fixes #342
=> fix(cli): change task runner return value from next to retry

packages/vscode-webui/src/components/tool-invocation/tools/new-task/use-live-sub-task.tsx, packages/vscode-webui/src/features/approval/hooks/use-pending-retry-approval.ts
This PR refactors the retry count management to be more precise:
- Reset retry count when status is ready and no error exists
- Move retry count reset logic to be based on execution status rather than step count
- Ensure proper dependency tracking in useEffect hooks
Fixes the issue where retry count was being reset incorrectly during task execution.
Fixes: https://github.com/TabbyML/pochi/issues/342
=> fix(vscode-webui): improve retry count management logic

packages/tools/src/index.ts, packages/vscode-webui/src/features/chat/hooks/use-chat-status.ts
- Updated the chat status hook to properly filter out user input tools and auto-approved tools when determining if the chat is in a previewing state
- Modified `isUserInputToolPart` to use `getToolName` and `isToolUIPart` for better type safety
- Updated `isAutoApproveTool` to use `getToolName` for consistency
- Enhanced the `isPreviewing` calculation in `useChatStatus` hook to exclude both user input tools and auto-approved tools
This provides a more accurate representation of when the chat is actually waiting for user interaction versus when it's processing automatically approved tools.
- Verified that the updated functions work correctly
- Tested that the chat status hook properly filters previewing tool calls
- Ran existing test suites to ensure no regressions
🤖 Generated with …
=> fix(vscode): isPreviewing shall exclude UserInputTools and AutoApproveTools

packages/vscode-webui/src/components/dev-mode-button.tsx, packages/vscode-webui/src/features/chat/components/chat-toolbar.tsx
- Removed the environment building logic from the chat toolbar component
- Updated the DevModeButton component to no longer require the buildEnvironment prop
- Simplified the component structure and reduced unnecessary dependencies
- Verified that all existing tests pass
- Confirmed that the PR branch builds successfully
- Checked that the changes don't introduce any new type errors
🤖 Generated with Pochi
=> refactor(vscode-webui): remove environment building from chat toolbar and dev mode button

packages/vscode/src/integrations/webview/base.ts, packages/vscode/src/integrations/webview/pochi-webview-panel.ts, packages/vscode/src/integrations/webview/webview-sidebar.ts
- Added LogoPathSegments constant in base class (following PascalCase naming)
- Created buildResourceURI helper method for consistent resource URI building
- Created getLogoIconPath static method for VS Code icon paths
- Refactored both webview implementations to use shared helpers
- Removed unused getUri imports
=> refactor(vscode): reduce duplication in logo128.png usage

packages/livekit/src/chat/middlewares/new-task-middleware.ts, packages/tools/src/index.ts, packages/tools/src/new-task.ts, packages/vscode-webui/src/features/settings/components/sections/tools-section.tsx
- Extract the newTask tool input schema into a separate export to enable reusing it in validation logic
- Clean up the tools-section component in vscode-webui to use a more direct approach for displaying tool descriptions
- Remove unused import in new-task-middleware.ts that was automatically detected by the pre-push hook
This refactor makes the newTask input schema reusable across different parts of the codebase, which will be helpful for consistent validation. The vscode-webui changes simplify how tool descriptions are displayed.
=> refactor(tools): extract newTask input schema for reuse

bun.lock, packages/livekit/package.json, packages/livekit/src/chat/models/google-vertex-tuning.ts
- Enabled thinking configuration for the Google Vertex tuning model to include thoughts in model responses
- Set a thinking budget of 4096 tokens for better contextual responses
- Added missing @ai-sdk/google dependency to the livekit package
=> feat(livekit): enable thinking configuration for Google Vertex tuning model

packages/common/src/vscode-webui-bridge/webview-stub.ts, packages/common/src/vscode-webui-bridge/webview.ts, packages/vscode-webui/ambient.d.ts, packages/vscode-webui/src/lib/vscode.ts, packages/vscode-webui/src/livestore-provider.tsx, packages/vscode-webui/src/routes/tasks.tsx, packages/vscode/src/integrations/webview/base.ts, packages/vscode/src/integrations/webview/pochi-webview-panel.ts, packages/vscode/src/integrations/webview/vscode-host-impl.ts, packages/vscode/src/integrations/webview/webview-sidebar.ts
- Added bridgeStoreEvent API to VSCodeHostApi interface to enable communication between webview pane and sidebar
- Implemented commitStoreEvent in the webview to handle store events from the pane webview
- Created a proxy store in pane webviews that forwards commits to the sidebar for synchronization
- Set up proper webview kind detection (sidebar vs pane) using ambient type definitions
- Ensured changes made in individual task tabs are properly synchronized with the main sidebar view
=> feat(vscode): allow webview pane (individual tab) sync with webview sidebar through bridgeStoreEvent

packages/cli/src/tools/edit-notebook.ts, packages/cli/src/tools/index.ts, packages/common/src/tool-utils/__tests__/notebook-utils.test.ts, packages/common/src/tool-utils/index.ts, packages/common/src/tool-utils/notebook-utils.ts, packages/vscode/src/tools/edit-notebook.ts, rules/no-workspace-folders.yaml
- Created shared notebook utilities in @getpochi/common/tool-utils:
- validateNotebookPath() - validates .ipynb extension
- validateNotebookStructure() - validates notebook structure
- parseNotebook() - parses and validates notebook JSON
- editNotebookCell() - edits cell by ID or index
- serializeNotebook() - serializes to formatted JSON
- Implemented editNotebook tool for CLI package using shared utilities
- Refactored VSCode editNotebook to use shared utilities, eliminating code duplication
- Added comprehensive tests (15 tests) for all notebook utilities
- All existing tests pass (102 VSCode tests + 15 new common tests)
Co-Authored-By: Pochi <noreply@getpochi.com>
=> feat(tools): add CLI implementation of editNotebook tool and extract common utilities
