TabbyML/pochi

.github/workflows/autofix.yml, .github/workflows/check.yml, .github/workflows/ci.yml
- Adds a new GitHub Actions workflow to automatically format and lint the codebase using `bun fix`.
- This workflow runs on `push` to the `main` branch and on `pull_request` events.
- It helps ensure code quality and consistency across the project.
- Push a change to a feature branch and open a PR.
- Verify that the `autofix` workflow runs.
- If there are formatting/linting issues, the workflow should fail.
- After running `bun fix` locally and pushing the changes, the workflow should pass.
=> feat(workflow): add autofix workflow

packages/common/src/base/prompts/index.ts, packages/livekit/src/chat/flexible-chat-transport.ts, packages/livekit/src/chat/generate-task-title.ts, packages/livekit/src/chat/live-chat-kit.ts, packages/livekit/src/livestore/schema.ts
This commit introduces the capability to automatically generate a title for a task based on the user message. This improves user experience by providing immediate context to the task.
🤖 Generated with [Pochi](https://getpochi.com/)
Co-Authored-By: Pochi <noreply@getpochi.com>
=> feat(chat): generate task title automatically 

packages/vscode/src/integrations/configuration.ts
Fixing https://discord.com/channels/1372983295628939349/1408720719918927872
- Add Zod schema validation for Pochi advanced settings
- Replace plain type definition with Zod schema for better type safety
- Parse configuration values with safeParse to handle invalid configurations gracefully
- Return empty object as fallback for invalid configurations
=> fix: add Zod validation for advanced settings configuration

packages/vscode/src/integrations/vscode-lm.ts
- **Enhanced VSCode LM integration** with improved abort handling using Promise.race
- **Added new utility function** promiseFromAbortSignal for clean abort signal integration  
- **Improved async iteration** by replacing direct async iteration with race condition handling
- **Better resource cleanup** ensuring proper disposal when requests are aborted
- **Removed debug logging** from VSCode LM requests to reduce noise
- **Enhanced error handling** in VSCode LM requests with more specific error messages
The main changes are in packages/vscode/src/integrations/vscode-lm.ts:
1. **Replaced direct async iteration** with a Promise.race pattern that properly handles abort signals
2. **Added promiseFromAbortSignal utility** that creates a promise that rejects when the abort signal fires
3. …
=> feat(vscode): enhance VSCode LM integration with improved abort handling

packages/cli/src/cli.ts
This PR updates the user agent format in the CLI to follow the naming convention.
=> chore(cli): update ua format to follow the naming convention

packages/vscode-webui/src/features/chat/hooks/use-chat-submit.ts, packages/vscode-webui/src/features/chat/lib/tool-call-life-cycle.ts
- Add proper state transitions for tool call abort functionality
- Improve handling of user abort scenarios in tool call lifecycle
- Remove debug console.log statement
This addresses issues with tool call state management when users abort operations.
=> fix(vscode-webui): improve tool call lifecycle management and chat submission

packages/cli/src/tools/execute-command.ts, packages/livekit/src/chat/live-chat-kit.ts
- Extract command output processing logic into a dedicated function in the CLI executeCommand tool
- Include exit code information in command output when non-zero for better debugging
- Add error logging and exit on chat errors in LiveKit for better error handling
=> fix: Enhance executeCommand output processing and fix LiveKit error handling

packages/docs/content/docs/cli.mdx
* Update CLI version from v0.5.3 to v0.5.5 in documentation
* Improve formatting of command line options documentation for better readability
* Add detailed explanation of workflow usage with practical examples
* Fix text wrapping issues throughout the CLI documentation
This PR ensures the CLI documentation accurately reflects the current capabilities and usage patterns of the Pochi CLI tool, making it easier for users to understand and utilize all available features.
=> docs(cli): update CLI documentation with latest usage information

packages/docs/content/docs/cli.mdx, packages/docs/content/docs/slack.mdx
- Add debugging section to CLI documentation with environment variable usage examples
- Reorganize Slack documentation by renaming Troubleshooting to Frequently Asked Questions
- Improve clarity of common Slack issues with more concise explanations
=> docs: update CLI debugging info and reorganize Slack FAQ

bun.lock, packages/common/src/vscode-webui-bridge/webview-stub.ts, packages/common/src/vscode-webui-bridge/webview.ts, packages/vscode-webui/src/components/prompt-form/auto-completion/extension.ts, packages/vscode-webui/src/components/prompt-form/auto-completion/mention-list.tsx, packages/vscode-webui/src/components/prompt-form/form-editor.tsx, packages/vscode-webui/src/lib/vscode.ts, packages/vscode/package.json, packages/vscode/src/integrations/webview/vscode-host-impl.ts
=> feat(vscode): introduce listAutoCompleteCandidates function

packages/vscode/src/integrations/uri-handler.ts
- This fix prevents the "new workspace" prompt from appearing when creating a project in a remote Pochi environment.
N/A
=> fix(website): should not prompt new workspace when creating in remote pochi

.github/workflows/release-pochi-cli.yml
POCHI_HOMEBREW_GITHUB_TOKEN added in pochi secret
test CI: https://github.com/zwpaper/pochi/actions/runs/17426214634/job/49473787096
=> feat(ci): automate homebrew formula updates on release

packages/vscode-webui/src/share.tsx
=> fix(vscode): add i18n config in share and task page

.github/workflows/release-pochi-cli.yml, packages/cli/README.md, packages/cli/package.json, packages/cli/scripts/build-cli.sh, packages/cli/scripts/npm-release.ts, packages/cli/tsconfig.json, packages/cli/turbo.json, scripts/dep-check.ts, tsconfig.json
released with name `@getpochi/pochi`
local test with custom name:
=> ci(release): upload pochi cli in node to npm in cli release

.pochi/workflows/generate-dev-updates.md, packages/docs/content/docs/developer-updates.mdx
This week's(Aug 29th - Sep 5th) dev updates.
- I added a **New Contributors** section. Let me know if it's okay.
- We did ship A LOT in the past week 💪. And I let go a lot of PRs in https://github.com/TabbyML/pochi/pull/154/commits/85cc7ffd2984a145f3fcda1a57815e630a46e85f, let me know if anything needs to be put back.
=> docs: Weekly developer updates(Aug 30th - Sep 5th, 2025)

assets/config.schema.json, packages/cli/src/cli.ts, packages/cli/src/model/cmd.ts, packages/common/src/base/constants.ts, packages/common/src/configuration/model.ts, packages/common/src/vendor/types.ts, packages/common/src/vscode-webui-bridge/types/model.ts, packages/vscode-webui/src/components/token-usage.tsx, packages/vscode-webui/src/features/chat/lib/use-live-chat-kit-getters.ts, packages/vscode/src/integrations/command.ts
This PR makes the `contextWindow` and `maxTokens` properties optional in the model configuration. Default values are now provided when these properties are not specified, ensuring that the application can handle models with missing or incomplete information.
- Run existing tests to ensure no regressions.
=> fix: Make model options optional and provide default values

packages/vscode-webui/src/features/chat/lib/use-live-chat-kit-getters.ts
fix: improve checkpoint handling and add debug logging
- Change checkpoint logic to find second-to-last checkpoint instead of last
- Add debug logging to track snapshot requests
- Reverse iteration order for more efficient checkpoint searching
=> fix: improve checkpoint handling and add debug logging

packages/vscode/src/integrations/command.ts
- Add more descriptive prompt text mentioning Pochi website for clarity
- Set password: true to mask token input for improved security
- Clean up extra blank line for better code formatting
=> chore: improve login token input dialog

packages/common/src/base/prompts/__tests__/__snapshots__/prompt.test.ts.snap, packages/common/src/base/prompts/index.ts, packages/common/src/base/prompts/system.ts, packages/livekit/src/chat/flexible-chat-transport.ts, packages/tools/src/index.ts, packages/tools/src/new-task.ts
- Remove overrideCustomAgents function and general-purpose agent defaults
- Consolidate system prompt creation to handle custom agents within main function
- Simplify custom agent tool description generation
- Update imports and exports across affected modules
- All existing tests should pass after snapshot updates
- Verify that custom agent functionality works as expected
- Ensure system prompt generation handles both regular and custom agent scenarios correctly
=> refactor: simplify custom agent system prompt handling

-H, packages/livekit/src/chat/models/openai.ts
fix https://github.com/TabbyML/pochi/issues/13
=> fix: properly set max_completion_tokens for openai reasoning models

bun.lock, packages/cli/src/cli.ts, packages/cli/src/lib/__tests__/load-agents.test.ts, packages/cli/src/lib/load-agents.ts, packages/cli/src/output-renderer.ts, packages/cli/src/task-runner.ts, packages/cli/src/tools/new-task.ts, packages/cli/src/types.ts, packages/common/package.json, packages/common/src/tool-utils/__tests__/agent-parser.test.ts, packages/common/src/tool-utils/agent-parser.ts, packages/common/src/tool-utils/index.ts, packages/livekit/src/chat/flexible-chat-transport.ts, packages/livekit/src/chat/live-chat-kit.ts, packages/vscode/package.json, packages/vscode/src/lib/custom-agent.ts
This PR introduces the following features:
- An agent parser to handle agent configurations.
- An agent loader to load agents in the CLI.
- Unit tests for the agent parser and loader have been added.
=> feat(agent): add agent parser and loader

.pochi/workflows/create-issue.md, packages/cli/src/auth/cmd.ts, packages/cli/src/cli.ts, packages/cli/src/mcp/__tests__/list.test.ts, packages/cli/src/mcp/cmd.ts, packages/cli/src/mcp/list.ts, packages/cli/src/model/cmd.ts, packages/cli/src/task/cmd.ts, packages/cli/src/task/list.ts, packages/cli/src/task/share.ts, packages/cli/src/upgrade/cmd.ts
This commit enhances the user experience of the Pochi CLI by providing clearer and more detailed descriptions for all major commands and their options. The help messages have been updated to be more informative, guiding users on how to effectively use each command.
- All tests pass, including the one that was fixed.
=> refactor(cli): improve command descriptions and help messages

.pochi/workflows/create-plan.md, .pochi/workflows/generate-tasks.md, .pochi/workflows/process-tasks.md
=> docs(workflows): add guidelines for generating plans and managing task lists

packages/vscode-webui/.storybook/preview.tsx, packages/vscode-webui/src/components/__stories__/model-select.stories.tsx, packages/vscode-webui/src/components/model-select.tsx, packages/vscode-webui/src/components/ui/tooltip.tsx, packages/vscode-webui/src/features/chat/components/chat-toolbar.tsx, packages/vscode-webui/src/features/chat/hooks/use-chat-status.ts, packages/vscode-webui/src/features/chat/page.tsx, packages/vscode-webui/src/features/settings/hooks/use-selected-models.ts, packages/vscode-webui/src/features/settings/store.ts, packages/vscode-webui/src/i18n/locales/en.json, packages/vscode-webui/src/i18n/locales/jp.json, packages/vscode-webui/src/i18n/locales/ko.json, packages/vscode-webui/src/i18n/locales/zh.json
https://jam.dev/c/1431986f-859a-4f58-9efc-17f7b8dea0cd
- Add tooltip to model unavailable warning icon with responsive width
- Enhance model selection to store DisplayModel objects instead of just IDs
- Improve model validation logic to prevent submission when model is invalid
- Add internationalization support for model unavailable message in 4 languages
- **Model Selection**: Refactor to store complete DisplayModel objects for better state management
- **Tooltip Enhancement**: Add informative tooltip to triangle alert icon when model is unavailable
- **Validation Logic**: Integrate model validity checks throughout chat workflow
- **Internationalization**: Add model unavailable messages in English, Chinese, Japanese, and Korean
- **UI/UX**: Responsive tooltip width and consistent styling …
=> fix(webui): retain selection and show alert when model is unavailable

packages/livekit-cf/package.json, packages/livekit-cf/src/do/livestore-client/app.ts, packages/livekit-cf/src/do/livestore-client/types.ts, packages/livekit-cf/src/lib/jwt.ts, packages/livekit/src/livestore/queries.ts, packages/tools/src/new-task.ts, packages/vscode-webui/src/features/share/page.tsx
- Add JWT verification for private shared tasks
- Implement subtask collection and inlining for UI display
- Add authorization check for private task access
- Rename DeepWriteable to DeepWritable for consistency
- Export verifyJWT function for external use
- Add makeSubTaskQuery for fetching subtasks
- Update SubTask type to remove uid field
- Add token authentication support in VSCode web UI
=> feat: Implement subtasks in share functionality with authentication

packages/livekit/src/react.tsx, packages/vscode-webui/src/components/tool-invocation/tools/new-task/use-live-sub-task.tsx, packages/vscode-webui/src/features/chat/page.tsx, packages/vscode-webui/src/providers.tsx
This PR improves workspace handling and optimizes React Query cache persistence in the VSCode WebUI:
- **Add cwd dependency to LiveChatKit**: Added `props.cwd` to the useMemo dependency array in `packages/livekit/src/react.tsx` to ensure proper workspace context when the current working directory changes.
- **Fix workspace cwd handling in useLiveSubTask**: Updated `packages/vscode-webui/src/components/tool-invocation/tools/new-task/use-live-sub-task.tsx` to properly handle workspace current working directory with explicit fallback to "default" when cwd is undefined.
- **Refactor workspace state management in Chat component**: Improved `packages/vscode-webui/src/features/chat/page.tsx` by consolidating workspace state management and ensuring proper fallback handling for the current …
=> feat(vscode-webui): improve workspace handling and query cache optimization

packages/vendor-claude-code/src/model.ts, packages/vendor-claude-code/src/vendor.ts
https://jam.dev/c/6e81b757-ee1f-4e56-93e8-459ee36926ef
This pull request improves model selection and display logic in the CLI, making it easier for users to select models by either their internal ID or display name, and clarifies model listing output. The changes also update model metadata for the Claude vendor to use more accurate display names and tool call middleware settings.
* Updated model selection in `createLLMConfigWithVendors` and `createLLMConfigWithProviders` to allow users to specify models by either their internal ID or display name, improving flexibility and user experience. Error messages were also made more informative. [[1]](diffhunk://#diff-7a02f7d6513a60a87cae3086768db219f1908f2594dc77cd1a13a0107cbb24e3R244-R272) …
=> refactor(cli): improve model ID handling and adding name for ModelOptions

.vscode/launch.json, .vscode/tasks.json, packages/livekit-cf/src/do/livestore-client/do.ts, packages/livekit-cf/src/lib/jwt.ts, packages/livekit-cf/src/lib/server.ts
… cf with local server
- auto run livekit-cf and vscode ext:
- task sync to local server
=> chore(dev): add local sync and local server debugger to debug livekit cf with local server

packages/vendor-claude-code/src/model.ts, packages/vendor-claude-code/src/vendor.ts
=> chore(vendor): name id claude code

packages/vscode-webui/src/components/__stories__/reasoning-part.stories.tsx, packages/vscode-webui/src/components/message/message-list.tsx, packages/vscode-webui/src/components/reasoning-part.tsx
- Implement smooth fade transition when reasoning headline changes
- Extract headline text from markdown content dynamically
- Add debounce state management for headline updates
- Improve visual feedback during assistant thinking process
=> feat(vscode-webui): add animated headline for reasoning component

packages/common/src/cors-proxy/index.ts, packages/common/src/cors-proxy/server.ts, packages/common/src/vendor/edge.ts, packages/livekit/ambient.d.ts, packages/livekit/src/chat/models/anthropic.ts, packages/vendor-claude-code/src/model.ts, packages/vendor-codex/src/model.ts, packages/vscode/src/integrations/webview/ragdoll-webview-provider.ts
- Update CORS proxy implementation with improved handling
- Enhance vendor edge functionality
- Update LiveKit ambient types and Anthropic model
- Improve VS Code webview provider integration
=> refactor: update cors proxy and vendor edge implementations

.github/workflows/release-pochi-cli.yml, .github/workflows/release-pochi-npm.yml, packages/cli/scripts/build-cli.sh
=> fix(npm): use bun 1.2.15 to build npm package

.vscode/launch.json, biome.json, packages/vscode/package.json, packages/vscode/src/code-completion/index.ts, packages/vscode/src/code-completion/utils/strings.ts, packages/vscode/src/extension.ts, packages/vscode/src/integrations/command.ts, packages/vscode/src/integrations/configuration.ts, packages/vscode/src/nes/cache.ts, packages/vscode/src/nes/client/google-vertex-tuning.ts, packages/vscode/src/nes/client/index.ts, packages/vscode/src/nes/client/type.ts, packages/vscode/src/nes/constants.ts, packages/vscode/src/nes/contexts.ts, packages/vscode/src/nes/decoration-manager.ts, packages/vscode/src/nes/edit-history.ts, packages/vscode/src/nes/git/git-state.ts, packages/vscode/src/nes/git/git.d.ts, packages/vscode/src/nes/index.ts, packages/vscode/src/nes/solution.ts, packages/vscode/src/nes/types.ts
=> feat(vscode): add experimental nes impl.

packages/cli/src/cli.ts, packages/cli/src/json-renderer.ts, packages/cli/src/task-runner.ts, packages/livekit/src/chat/chat-with-hook.ts, packages/livekit/src/chat/flexible-chat-transport.ts, packages/livekit/src/chat/live-chat-kit.ts, packages/livekit/src/chat/mcp-utils.ts, packages/vscode-webui/src/components/tool-invocation/mcp-tool-call.tsx, packages/vscode/src/integrations/webview/base.ts
=> feat(chat): use store-blob for mcp returned images

packages/common/src/base/environment.ts, packages/common/src/base/prompts/environment.ts, packages/common/src/vscode-webui-bridge/webview.ts, packages/tools/src/edit-notebook.ts, packages/tools/src/index.ts, packages/vscode-webui/src/components/prompt-form/active-selection-badge.tsx, packages/vscode-webui/src/components/tool-invocation/index.tsx, packages/vscode-webui/src/components/tool-invocation/tools/edit-notebook.tsx, packages/vscode-webui/src/features/settings/components/sections/tools-section.tsx, packages/vscode/src/integrations/editor/tab-state.ts, packages/vscode/src/integrations/webview/vscode-host-impl.ts, packages/vscode/src/tools/edit-notebook.ts
https://jam.dev/c/89c5ce5a-a000-4fc0-9daf-67d31dd48ae4
- Added new `editNotebook` tool to enable editing of individual Jupyter notebook cells by cell ID or index
- Enhanced active selection tracking to include notebook cell information (cell index and cell ID)
- Updated UI components to display notebook cell information in active selection badges
- Implemented notebook file opening with cell navigation support
**Core Tool Implementation:**
- Added `editNotebook` tool in `packages/tools/src/edit-notebook.ts` that edits specific cells in `.ipynb` files by cell ID
- Integrated the tool into VSCode extension at `packages/vscode/src/tools/edit-notebook.ts`
**Environment & Selection Tracking:**
- Extended `Environment` schema to include `notebookCell` metadata (cell index and ID) in active …
=> feat(notebook): add editNotebook tool for modifying Jupyter notebook cells

bun.lock, packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/task-runner.ts, packages/livekit/src/chat/flexible-chat-transport.ts, packages/livekit/src/chat/live-chat-kit.ts, packages/livekit/src/chat/llm/repair-tool-call.ts, packages/livekit/src/chat/middlewares/new-task-middleware.ts, packages/livekit/src/chat/middlewares/output-schema-middleware.ts, packages/tools/src/attempt-completion.ts, packages/tools/src/index.ts
- Add output schema middleware for LiveKit chat to ensure structured responses
- Add output schema utilities in CLI for better response handling
- Enhance tools with structured response capabilities using Zod validation
- Add Zod as a dependency to the CLI package
This feature enables more predictable and structured responses from AI models, making it easier to integrate with downstream systems that require specific data formats.
=> feat(experimental, cli): implement output schema support for structured responses

assets/install.sh, packages/docs/content/docs/cli.mdx
- Allow users to specify a version when installing via the install script
- Update CLI documentation to show how to install specific versions
- Fix parsing logic in install script
=> feat(install): add support for installing specific versions

packages/cli/src/cli.ts, packages/cli/src/lib/mcp-hub-factory.ts, packages/common/src/configuration/config-file.ts, packages/common/src/configuration/config-manager.ts, packages/common/src/configuration/index.ts, packages/common/src/mcp-utils/__tests__/mcp-hub.test.ts, packages/common/src/mcp-utils/mcp-hub.ts, packages/vscode/src/extension.ts, packages/vscode/src/integrations/checkpoint/checkpoint-service.ts, packages/vscode/src/integrations/command.ts, packages/vscode/src/integrations/configuration.ts, packages/vscode/src/integrations/mcp/index.ts, packages/vscode/src/integrations/mcp/mcp-hub-factory.ts, packages/vscode/src/integrations/mcp/third-party-mcp/importer.ts, packages/vscode/src/integrations/webview/vscode-host-impl.ts, packages/vscode/src/lib/custom-agent.ts, packages/vscode/src/lib/workspace-scoped.ts, rules/no-workspace-folders.yaml
=> feat: re-enable workspace configuration handling

packages/cli/src/json-renderer.ts
- Track output message IDs to prevent duplicate outputs
- Messages are finalized when a new message appears after them
- On shutdown, output any remaining messages that haven't been output yet
- Refactor logic into a dedicated outputMessages helper method
This change fixes an issue with messages being output multiple times during updates by implementing a proper deduplication mechanism.
=> refactor(cli): ensure each message is output only once when finalized
